#!/bin/sh
# When placed in hooks/ directory of a bare Git repository, this post-update hook script checks out HEAD to the
# /var/www/repo-name (without the .git suffix).


dst=../../www/$(basename $(pwd -P) | sed 's/\.git//g')
realdst=`readlink -f $dst`
hostname=`hostname -f`

if [ -d $dst ] ; then
    if `git --work-tree=$dst --git-dir=. checkout -f`; then
        echo "Completed deployment to $(realpath $dst) on $hostname"
        exec git update-server-info
    fi
else
    echo "Deployment on $hostname failed!"
    exec git update-server-info
    exit 1
fi
