#!/bin/bash

# Create directories/files
mkdir -p /tmp/email-backup/Gmail
#mkdir -p /tmp/email-backup/MobileMe
touch /tmp/email-backup/Gmail/All_Mail.mbox
touch /tmp/email-backup/Gmail/Sent_Mail.mbox
touch /tmp/email-backup/Gmail/Spam.mbox
touch /tmp/email-backup/Gmail/Backup_Logs.mbox
#touch /tmp/email-backup/MobileMe/*.mbox

# Backup Gmail mailboxes, tar and remove source files.
getmail -r /home//.getmail/gmail_All_Mail
tar cvjf /mnt/usb_backup/Backups/Email/Gmail_Archive/All_Mail.tar.bz2 /tmp/email-backup/Gmail/All_Mail.mbox

getmail -r /home//.getmail/gmail_Backup_Logs
tar cvjf /mnt/usb_backup/Backups/Email/Gmail_Archive/Backup_Logs.tar.bz2 /tmp/email-backup/Gmail/Backup_Logs.mbox

getmail -r /home//.getmail/gmail_Sent_Mail
tar cvjf /mnt/usb_backup/Backups/Email/Gmail_Archive/Sent_Mail.tar.bz2 /tmp/email-backup/Gmail/Sent_Mail.mbox

getmail -r /home//.getmail/gmail_Spam
tar cvjf /mnt/usb_backup/Backups/Email/Gmail_Archive/Spam.tar.bz2 /tmp/email-backup/Gmail/Spam.mbox

# Backup Gmail mailboxes, tar and remove source files.
#getmail -r /home//.getmail/mobileme_Archive
#tar cvjf /mnt/usb_backup/Backups/Email/MobileMe_Archive/All_Mail.tar.bz2 /tmp/email-backup/MobileMe/Archive.mbox



rm -rfv /tmp/email-backup/*


#if file exists mark as successful, add to email
