#!/bin/bash

COMPLETEJOBS=/tmp/overnight-jobs.log

if [ -f $COMPLETEJOBS ]

then
	cat $COMPLETEJOBS | sendemail -f  -t  -s  -o username= -o password= -u "Overnight jobs report from "
	rm -fv $COMPLETEJOBS
else
	echo "No jobs have run last night / Nothing to report" | sendemail -f  -t  -s  -o username= -o password= -u "No jobs to report for "
fi
